apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: project-test-backstage
  annotations:
    github.com/project-slug: maocq/project-test-backstage
spec:
  type: other
  lifecycle: unknown
  owner: maocq
